# Uncomment this line to define a global platform for your project
 platform :ios, '10.0'

target 'Tickets' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'FirebaseDatabase'
pod 'GoogleSignIn'


  # Pods for Tickets

end
